version: '3.1'

services:
  db:
    image: postgres:14.2-alpine
    env_file: .env
    volumes:
      - ./postgresdata:/var/lib/postgresql/data

  dbCloud:
    image: postgres:14.2-alpine
    env_file: .envcloud
    volumes:
      - ./postgresdatacloud:/var/lib/postgresql/data


  app:
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/app:/app:delegated
    env_file: .env
    environment:
      - BASE_URL=$APP_URL:$EXPOSE_PORT
    ports:
      - $EXPOSE_PORT:80

  cloud:
    image: nextcloud
      #     restart: always
    ports:
      - 8080:80
    links:
      - dbCloud
    volumes:
      - ./nextcloud:/var/www/html
    env_file: .envcloud 
