version: '3.1'

services:
  db:
    image: postgres:14.2-alpine
    env_file: .env
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always

  app:
    image: yiisoftware/yii2-php:8.0-apache
    restart: always
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/app:/app:delegated
    env_file: .env
    environment:
      - BASE_URL=$APP_URL:$EXPOSE_PORT
    ports:
      - $EXPOSE_PORT:80

