version: '3.1'

services:
  db:
    image: postgres:14.2-alpine
    env_file: .env
    volumes:
      - ./postgresdata:/var/lib/postgresql/data

  app:
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/app:/app:delegated
    env_file: .env
    ports:
      - 8000:80

  #cloud:
  #  image: nextcloud
  #  restart: always
  #  ports:
  #    - 8080:80
  #  links:
  #    - db
  #  volumes:
  #    - ./nextcloud:/var/www/html
  #  environment:
  #    POSTGRES_PASSWORD: test123
  #    POSTGRES_DB: testdb
  #    POSTGRES_USER: test
  #    POSTGRES_HOST: db
