<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'view_contests' => 'Ver más concursos',
    'welcome' => 'Sistema de Concursos',
    'sign_password' => 'Clave',
    'signup_first_name' => 'Nombres',
    'signup_last_name' => 'Apellidos',
    'signup_email' => 'Email',
    'sign_document' => 'CUIL',
    'login_title'=> 'Iniciar sesión',
    'login_remember_me' => 'Recordarme',
    'signup_user_unique_error' => 'Verifique los datos, el CUIL o el Email ya se encuentran registrados.',
    'signup_title' => 'Registrarse',
    'first_name' => 'Nombres',
    'last_name' => 'Apellidos',
    'real_address' => 'Dirección real',
    'legal_address' => 'Dirección legal',
    'cellphone' => 'Celular',
    'phone' => 'Teléfono fijo',
    'dni' => 'D.N.I',
    'date_of_birth' => 'Fecha de nacimiento',
];
