<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'home' => '',
    'signup_password' => 'Password',
    'signup_first_name' => 'First name',
    'signup_last_name' => 'Last name',
    'signup_email' => 'Email',
    'signup_document' => 'Document',
    'signup_user_unique_error' => 'Check document and email.',
    'signup_title' => 'Signup',
    'view_contests' => 'View contests',
    'welcome' => 'Sistema de Concursos',
    'login_title'=> 'Login',
    'login_remember_me' => 'Remember me',
    'signup_user_unique_error' => 'User identifier or email is invalid.',
    'first_name' => 'First name',
    'contact_email' => 'Email',
    'last_name' => 'Last name',
    'real_address' => 'Real address',
    'legal_address' => 'Legal address',
    'cellphone' => 'Cellphone',
    'phone' => 'Phone',
    'dni' => 'Document Identifier',
    'date_of_birth' => 'Date of birth',
    'save_button' => 'Save',
    'postulations' => 'My postulations',
    'terms_accepted_article_22' => 'Article 22 (Res. CD CURZA N 112/1991): The presentation of the application for registration matters, for
part of the applicant, the knowledge and acceptance of the conditions established in this regulation',
    'confirm_data' => 'I DECLARE UNDER OATH NOT TO BE INVOLVED IN THE CAUSES OF DISQUALIFICATION FOR THE PERFORMANCE OF PUBLIC OFFICES',
    'inscription_button' => 'Apply',
    'contest_not_found' => 'Contest not found',
];
